jaffle_shop:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: '{{ env_var("PROJECT_NAME") }}'
      schema: '{{ env_var("DATASET") }}'
      threads: 4
      keyfile: ../key.json
      timeout_seconds: 600
      location: US # Optional, one of US or EU
      priority: interactive
      retries: 1
