config:
  send_anonymous_usage_stats: false
jaffle_shop:
  outputs:
    dev:
      dbname: '{{ env_var("DATABASE") }}'
      host: '{{ env_var("HOST") }}'
      password: '{{ env_var("PASSWORD") }}'
      port: '{{ env_var("PORT") | int }}'
      schema: '{{ env_var("SCHEMA") }}'
      threads: 8
      type: postgres
      user: '{{ env_var("USERNAME") }}'
    prod:
      dbname: '{{ env_var("DATABASE_NAME") }}'
      host: '{{ env_var("HOST") }}'
      password: '{{ env_var("PROD_PASSWORD") }}'
      port: '{{ env_var("PORT") | int }}'
      schema: '{{ env_var("PROD_SCHEMA") }}'
      threads: 8
      type: postgres
      user: '{{ env_var("PROD_USERNAME") }}'
  target: dev
