# this is what's used for local development and dbt runs
version: "3.4"

services:
  dbt:
    build:
      context: ./
      network: host
    volumes:
      - ./:/app
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      - DBT_PROFILES_DIR=/app/.dbt
      - SNOWFLAKE_ACCOUNT
      - SNOWFLAKE_USER
      - SNOWFLAKE_PASS
      - SNOWFLAKE_ROLE
      - SNOWFLAKE_DATABASE
      - SNOWFLAKE_WAREHOUSE
      - SNOWFLAKE_PERSONAL_SCHEMA
    command: "python simplehttp.py"