name: Run DBT on Merge to Main

on:
  push:
    # branches: [ "main" ]

jobs:
  run_on_merge:
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.HOST }}
      DATABASE: ${{ secrets.DATABASE }}
      USERNAME: ${{ secrets.PROD_USERNAME }}
      PASSWORD: ${{ secrets.PROD_PASSWORD }}
      PORT: ${{ secrets.PORT }}
      SCHEMA: ${{ secrets.PROD_SCHEMA }}

    steps:
      - uses: "actions/checkout@main"

      - name: install requirements
        run: pip install -q -r requirements.txt

      - name: dbt deps
        run: |
          cd project_goes_here 
          dbt deps
        
# do we need to point to a specific profile?
      - name: dbt run
        run: |
          cd project_goes_here 
          dbt seed --full-refresh
          dbt run --full-refresh --fail-fast
          dbt snapshot
          dbt test --fail-fast
