name: Run dbt on Merge to Main

on:
  push:
    branches: [ "main" ]

jobs:
  dbt_run_on_merge:
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.HOST }}
      DATABASE: ${{ secrets.DATABASE }}
      USERNAME: ${{ secrets.PROD_USERNAME }}
      PASSWORD: ${{ secrets.PROD_PASSWORD }}
      PORT: ${{ secrets.PORT }}
      SCHEMA: ${{ secrets.PROD_SCHEMA }}

    steps:
      - uses: "actions/checkout@main"

      - name: install requirements
        run: pip install -q -r requirements.txt

      - name: dbt deps
        run: |
          cd project_goes_here 
          dbt deps
        
      - name: dbt build
        run: |
          cd project_goes_here 
          dbt build --target prod
          dbt snapshot --target prod
