name: Manual dbt build - prod

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Manually trigger a dbt run'
        required: false
        type: boolean

jobs:
  run_dbt:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
      DATASET: ${{ secrets.DATASET }}
    steps:
    - uses: "actions/checkout@main"

    - name: Create file
      run: touch google-key.json | base64

    - name: Putting data
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $DATA > google-key.json

    - name: install requirements
      run: pip install -q -r requirements.txt

    - name: dbt deps
      run: |
        cd project_goes_here 
        dbt deps

    - name: dbt build
      run: |
        cd project_goes_here 
        dbt build --target prod
        dbt snapshot --target prod

