name: Scheduled dbt run - prod

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update_prod_target:
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.HOST }}
      DATABASE: ${{ secrets.DATABASE }}
      USERNAME: ${{ secrets.PROD_USERNAME }}
      PASSWORD: ${{ secrets.PROD_PASSWORD }}
      PORT: ${{ secrets.PORT }}
      SCHEMA: ${{ secrets.PROD_SCHEMA }}

    steps:
      - uses: "actions/checkout@main"

      - name: install requirements
        run: pip install -q -r requirements.txt

      - name: dbt deps
        run: |
          cd project_goes_here 
          dbt deps
        
      - name: dbt run
        run: |
          cd project_goes_here 
          dbt seed --full-refresh --select state:modified+
          dbt run --full-refresh --fail-fast --models state:modified+
          dbt snapshot
          dbt test --fail-fast
