name: scheduled clean up job - drop non-prod scheams

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Manually trigger a dbt run'
        required: false
        type: boolean
        
jobs:
  dbt_scheduled_cleanup_run:
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.HOST }}
      DATABASE: ${{ secrets.DATABASE }}
      USERNAME: ${{ secrets.PROD_USERNAME }}
      PASSWORD: ${{ secrets.PROD_PASSWORD }}
      PORT: ${{ secrets.PORT }}
      SCHEMA: ${{ secrets.PROD_SCHEMA }}

    steps:
      - uses: "actions/checkout@main"

      - name: install requirements
        run: pip install -q -r requirements.txt

      - name: dbt deps
        run: |
          cd project_goes_here 
          dbt deps
        
      - name: dbt run operation
        run: |
          cd project_goes_here 
          dbt run-operation drop_old_relations --args '{dry_run: "true"}'
